### ISSUE TITLE
camera not working

### ISSUE THREAD

**Issue by amoldeshmukh18** [Qengineering/TensorFlow_Lite_Pose_RPi_64-bits#1]
It is not working with my camera on raspberry pi 4B, the camera I am using using the official pi camera,  do you know how to get it working with raspi camera?

**Comment by Qengineering** [comment]
Indeed, it will not work with the RaspiCam. 
The 64-bit Ubuntu operating system doesn't support the official pi camera. 
You have three options: 
1) Use a simple webcam instead (see the end of this page https://qengineering.eu/install-ubuntu-18.04-on-raspberry-pi-4.html for details). 
2) Use the regular 32-bit Raspbian OS. Your app will be somewhat slower. 
3) Try to install the userland RaspiCam software under Ubuntu to get it working. (I never tried it, although some sites claim it is possible)

**Comment by amoldeshmukh18** [comment]
Hi I installed everything with Ubuntu 20.04 and edited the file /boot/firmware/config.txt added start_x=1 to the file and the camera is working for me. But the max fps I got was 6.7 not the 9+ fps you get, not a huge increase for me, previously I got about 4.5 FPS on the same h/w with Raspbian 32bit on raspberry pi 4B, 4GB RAM

**Comment by Qengineering** [comment]
Did you overclock your RPi?

**Comment by amoldeshmukh18** [comment]
When I add the line arm_freq=1925 to usercfg.txt the pi fails to boot and get stuck on an error could not get clk: -517

**Comment by Qengineering** [comment]
Same happens to me. Max frequency I got was 1825 MHz.

**Comment by amoldeshmukh18** [comment]
what FPS you got with that? It seems Ubuntu 64bit on raspi is a bit unstable for me. I guess the best way could have been to have 64 bit raspbian to achieve the faster speed.

**Comment by Qengineering** [comment]
A lot is happening since May 10. The Raspberry Foundation has released a new 64-bit OS with support of the Raspicam. And also good news, Ubuntu has the userland drivers incorporated into their repositories. So Raspicam can also be used in Ubuntu 18.04 - 20.04. We have updated our website with this information. (https://qengineering.eu/install-raspberry-64-os.html) On the subject of using deep learning networks on a 64-OS, Raspberry 64-OS gives the best results. Ubuntu is a bit slower. During startup, Ubuntu has a lot to do behind the curtains, so your deep learning app will suffer irregular frame rates. After 15 min or so, the OS is idle and can give you the best performance. Raspberry 64-OS doesn't have these issues.
